Extension/Xamarin-Extension/Overview.md

Hi @ChristoIssac,
Worked on Coverage issues, merge these changes.
Regards,
Gowthaman

SEO-1937_Coverage_Issues

---

Extension/ASPNETCore-EssentialJS2-Extension/Visual-Studio/Syncfusion-Project-Templates.md

**Content Changes Description**
I have changed the document of a syncfusion content - EJ2 CORE document, I have newly added the content about **Authentication Type** which I have newly provided the Support in Syncfusion **EJ2 CORE** Project, So that I have added the content in document about authentication and also I have added the respective images for the Authentication in UG document.

EXT-6719 UG document changes for EJ2 Core authentication support

---

Extension/ASPNET-MVC-Extension/Download-ASPNET-MVC-Extension.md
Extension/ASPNET-MVC-Extension/Sample-Creator.md

Worked on site audit issues, merge these changes,
Regards,
Gowthaman

SEO-2475_Site_Audit_Issues

---

Extension/Xamarin-Extension/Create-Project.md

Updated redirect link for extension.
Regards,
Sharly A.

SEO-3446 - Extension redirect links

---

Extension/Syncfusion-NuGet-Packages/NuGet-Packages.md

Added redirect link for extension.
Regards,
Sharly A.

SEO-3446 - Extension redirect link

---

Extension/NETMAUI-Extension/download-and-installation.md
Extension/NETMAUI-Extension/overview.md
Extension/NETMAUI-Extension/template-studio.md

Adding some correction in .NET MAUI UG Content

MAUI-4945- Update the UG content

---

Extension/Frequently-Asked-Questions/The-Syncfusion-templates-do-not-show-up-in-the-new-project-window-of-Visual-Studio-How-can-to-get-them-installed.md

Hi @Aishwarya-Ganesan ,
Have changed the redirect links, Please review.
Thanks.
Regards,
Edith.

SEO-172121-extension-controls

---

Extension/Syncfusion-NuGet-Packages/NuGet-Packages.md

Please review extension changes.
Regards,
Sharly A.

SEO-172146 - Extension http to https links

---

Extension/Syncfusion-NuGet-Packages/NuGet-Packages.md

Hi @MallikaRK , please review the changes.
Thanks.
Regards,
Edith.

SEO-172815-Extension-Http-changes

---

Extension/Syncfusion-NuGet-Packages/NuGet-Packages.md

Have changed Extension Page with redirect links.
Regards,
Yvone.

SEO-174775 Extension Page with Redirect

---

Extension/WPF-Extension/Add-Item.md
Extension/WPF-Extension/Template-Studio.md

I have committed the WPF Template Studio UG content changes.

EXT-175792

---

Extension/ASPNETCore-EssentialJS2-Extension/Visual-Studio/Sample-Creator.md
Extension/ASPNETCore-EssentialJS2-Extension/Visual-Studio/Syncfusion-Project-Templates.md
Extension/Blazor-Extension/Visual-Studio-Code/create-project.md
Extension/Blazor-Extension/Visual-Studio/template-studio.md
Extension/NETMAUI-Extension/template-studio.md
Extension/WPF-Extension/Add-References.md
Extension/WPF-Extension/Template-Studio.md
Extension/WindowsForms-Extension/Add-References.md
Extension/WindowsForms-Extension/Syncfusion-Project-Templates-for-Windows-Forms.md

I have modified the UG content of WPF Template Studio

EXT-1775- Modified the UG Content

---

Extension/WindowsForms-Extension/Syncfusion-Item-Templates-for-Windows-Forms.md
Extension/WindowsForms-Extension/Syncfusion-Project-Templates-for-Windows-Forms.md
Extension/WindowsForms-Extension/Template-Studio.md

I have committed the WF Template Studio  and WF ItemTemplate UG content changes.

EXT-175791 WinForm Extension UG updated

---

Extension/Syncfusion-NuGet-Packages/NuGet-Packages.md

Hello,
I have fixed the broken link.
Regards,
Beryl.

SEO-171361-Broken-Links-Extensions

---

Extension/Syncfusion-Reference-Manager/Add-a-Syncfusion-References-via-Syncfusion-Reference-Manger.md

Hi @gowthamanthavasiyappan,
Kindly review the referring links issue fixes changes.
Thanks.
Regards,
Edith.

SEO-180844-Extension-refering-page

---

Extension/Faq/How-to-get-rid-of-from-multiple-version-alert-message-in-Syncfusion-Xamarin-Toolbox.md
extension-toc.html

I have integrated the maui platform multiple nuget version alert faq contents.

Extension - FAQ Content change

---

Extension/Blazor-Extension/Visual-Studio/scaffolding.md

update Blazor scaffolding UG content

update Blazor scaffolding UG content

---

Extension/WPF-Extension/Template-Studio.md
Extension/WindowsForms-Extension/Template-Studio.md

1. The WinForms and WPF UG has been comprehensively updated to include sections on NuGet Entry, Dependency Injection (DI) Setup, PageServices integration, and details on managing Resource files. Additionally, existing content has been reviewed and refined to correct inaccuracies and eliminate duplicate information.

WinForms and WPF Template Studio UG Improvements

---

Extension/Document-Viewer-Extension/Visual-Studio-Code/download-and-installation.md
Extension/Document-Viewer-Extension/Visual-Studio-Code/getting-started.md

UG Right side Alignment changes

Alignment changes

---

extension-toc.html

TOC removed

---

extension-toc.html

I have included the Toc content include changes for document viewer extension

Document Viewer extension TOC changes

---

Extension/Document-Viewer-Extension/Visual-Studio-Code/FAQ.md
Extension/Document-Viewer-Extension/Visual-Studio-Code/configuration-options.md
Extension/Document-Viewer-Extension/Visual-Studio-Code/getting-started.md
Extension/Document-Viewer-Extension/Visual-Studio-Code/overview.md

Modified the document viewer extension UG content.

UG content changes

---

Extension/Document-Viewer-Extension/Visual-Studio-Code/getting-started.md
Extension/Document-Viewer-Extension/Visual-Studio-Code/overview.md

Document Viewer Extension UG content modified

UG updated
